fix: Return merged resources from recursive call.
moltin/gatsby-source-moltin pull request #43
Opened 2019-09-11 16:40 UTC by stuckj

2019-09-12 19:09 UTC, ynnoj requested changes

2019-09-12 19:09 UTC, ynnoj commented on gatsby-node.js
> +      var merged = merge(data, response)
`let`

2019-09-16 17:56 UTC, stuckj commented on gatsby-node.js
> +      var merged = merge(data, response)
Fixed.

2019-09-16 19:22 UTC, notrab approved these changes

2019-09-16 19:23 UTC, merged

2019-09-20 21:46 UTC, notrab commented
:tada: This PR is included in version 1.6.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@moltin/gatsby-source-moltin)
- [GitHub release](https://github.com/moltin/gatsby-source-moltin/releases/tag/v1.6.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: